[package]
name = "tyinfer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusttyc = "0.5.0"
blir = { path = "../blir" }
errors = { path = "../errors" }